### ISSUE TITLE
Multiple requests at same time with expired token all trigger a refresh request [bug]

### ISSUE THREAD

**Issue by paulrobello** [AlexAegis/auth#382]
**Describe the bug**
Multiple requests fired off at the same time with an expired token all trigger a refresh request with the current refresh token.
The first refresh request succeeds which invalidates the refresh token as they are one time use, then all the other refresh requests fail because the refresh token has already been used.

**To Reproduce**
Have app that makes more than 1 request to JWT protected api at launch with a JWT token and refresh token already stored in app from a previous session.
Server rejects all those requests because of invalid JWT token.
Library then initiates a refresh request for every failed request.
1st refresh request succeeds, all subsequent requests in that batch fail due to refresh token already being used.

**Expected behavior**
All requests are queued and only a single refresh attempt is made.

**Comment by AlexAegis** [comment]
I will definitely take a deeper look into this but I'll be busy all december so maybe only in january. I don't want a half-assed solution as I could potentionally introduce a bottleneck here.

**Comment by paulrobello** [comment]
Did you ever get a chance to look into this?

**Comment by AlexAegis** [comment]
@paulrobello Hey, a bit later than expected but I took a look and solved this problem! I'll do the backports later, maybe when I do the NG12 upgrade. :)
